### ISSUE TITLE
database

### ISSUE THREAD

**Issue by mhmtwork** [oguzyyilmaz/FriendOfMineServer#1]
veri olmasa bile bir sql yüklemeniz mümkün mü.

**Comment by oguzyyilmaz** [comment]
Soruyu biraz açar mısınız ?

14 Ağu 2017 ÖÖ 11:06 tarihinde "mhmtwork" <notifications@github.com> yazdı:

**Comment by mhmtwork** [comment]
projenin veritabanı nı kastetmeştim.

**Comment by oguzyyilmaz** [comment]
Projede nosql neo4j db var

15 Ağu 2017 ÖS 2:32 tarihinde "mhmtwork" <notifications@github.com> yazdı:

**Comment by oguzyyilmaz** [comment]
Veri yükleyip kullanmak isterseniz yardımcı olabilirim

15 Ağu 2017 ÖS 2:39 tarihinde "oguzhan yılmaz" <yilmazoguz94@gmail.com>
yazdı:

**Comment by mhmtwork** [comment]
teklifiniz için teşekkür ederim. Ben neo4j ye  çalışıp öyle geri döneyim.
